import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import { ThemeProvider } from "@/context/ThemeContext";
import { SidebarProvider } from "@/context/SidebarContext";
import { ToastProvider } from "@/context/ToastContext";
import RouteLoadingProvider from "@/context/RouteLoadingProvider";
import { AuthProvider } from "@/context/AuthContext";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "MHBilliards App",
    description: "Generated by Hiếu",
};

export const diabloFont = localFont({
    src: [
        {
            path: "../fonts/DiabloStd.otf", // đường dẫn đến font
            weight: "400", // hoặc nhiều weight nếu có
            style: "normal",
        },
    ],
    variable: "--font-diablo", // tạo CSS variable để dùng với Tailwind
});
export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${geistSans.variable} ${geistMono.variable} ${diabloFont.variable} antialiased`}
                suppressHydrationWarning>
                <RouteLoadingProvider>
                    <ThemeProvider>
                        <ToastProvider>
                            <SidebarProvider>
                                <AuthProvider>{children}</AuthProvider>
                            </SidebarProvider>
                        </ToastProvider>
                    </ThemeProvider>
                </RouteLoadingProvider>
            </body>
        </html>
    );
}
